POST http://localhost:3002/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDVhNmJjZjFhMjAxZjFkZWRhNjkxMyIsInVzZXJuYW1lIjoibWljaGVsbDI5IiwiaWF0IjoxNjQ4NzUwMjgzfQ.tPuzgy-zGp-cGhlLtEBeuG1fez_BaygfujsNlPuCG7s

{
    "content": "middleware",
    "important": false
}

###

POST http://localhost:3002/api/login
Content-Type: application/json

{
    "username": "michell29",
    "password": "123456789"
}